// Auto-generated by make — do not edit
let buildVersion = "0.6.5"
let buildCommit = "9af8465"
let buildBranch = "main"
let buildDate = "2026-03-31 12:23:13 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3"
