// Auto-generated by make — do not edit
let buildVersion = "1.0.0"
let buildCommit = "b88d2f0"
let buildBranch = "main"
let buildDate = "2026-04-12 21:16:11 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
