// Auto-generated by make — do not edit
let buildVersion = "0.6.7"
let buildCommit = "82fdf29"
let buildBranch = "main"
let buildDate = "2026-03-31 12:50:24 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
